"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

Quick-start development settings - unsuitable for production
See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
"""

import os
from .env import env, BASE_DIR

PROJECT_NAME = env('PROJECT_NAME', default='Test')

DOMAIN = env('DOMAIN', default='localhost')

SECRET_KEY = env('DJANGO_SECRET_KEY')

DEBUG = env('DEBUG', default=False)

IS_TEST = env('IS_TEST', default=False) # Unused currently

DISABLE_REGISTRATION = env('DISABLE_REGISTRATION', default=False)

ALLOWED_HOSTS = [env('DOMAIN', default='localhost')]

if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1']

ENABLE_OTP_ADMIN = True
ADMIN_USER = env('ADMIN_USER', default='admin@admin.com')
ADMIN_MASTERPASS = env('ADMIN_MASTERPASS', default='1234')

# Application definition

# TODO ADD
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',

    # REST API
    'rest_framework',
    'rest_framework.authtoken',

    # Auth
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',  # needed, cause bug https://github.com/Tivix/django-rest-auth/issues/412
    'dj_rest_auth.registration',

    # Admin tools
    'admin_tools',
    'admin_tools.theming',
    'admin_tools.menu',
    'admin_tools.dashboard',

    # IP
    'django_user_agents',

    # Internal apps
    'core',
    'users',

    'drf_spectacular',
    'django_filters',
    'django_countries',
    'corsheaders',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'rangefilter',    
]

# TODO ADD
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # New
    # 'core.middleware.force_default_language_middleware', # New
    # 'core.middleware.SetupTranslationsLang', # New
    'corsheaders.middleware.CorsMiddleware', # New
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware', # New
    # 'core.middleware.AccessLogsMiddleware', # New
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'maintenance_mode.middleware.MaintenanceModeMiddleware', # New
    # 'core.middleware.ResponseTimeMiddleware', # New

    # Odd
    'allauth.account.middleware.AccountMiddleware',
]



ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'loaders': [
                'admin_tools.template_loaders.Loader',
                'django.template.loaders.filesystem.Loader',    
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Optional: Configure OTP settings
OTP_TOTP_ISSUER = 'Test'
OTP_LOGIN_URL = '/admin/login/'